[package]
name = "SaikaTunnel"
version = "0.1.0"
edition = "2024"
default-run = "SaikaTunnel"

[dependencies]
ratatui = "0.25"
crossterm = "0.27"
ctrlc = "3.1"
colored = "2.0"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"